Bookmark/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('add', views.AddBookmark, name='add_mark'),
    path('delete/<int:pk>', views.Delete_mark.as_view(), name='delete_mark')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Bookmark.urls')),
    path('user/', include('user.urls'))
]

user/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('login_user/', views.LoginUser, name='login_user'),
    path('logout/', views.Logout, name='logout'),
    path('register/', views.Register, name='register'),
]

Bookmark/models.py
from django.db import models
from django.urls import reverse


class Bookmarks(models.Model):
    title = models.CharField(max_length=100)
    url = models.URLField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    create_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey('auth.User', related_name='mark', on_delete=models.CASCADE, blank=True)

    def get_absolute_url(self):
        return reverse('delete_mark', kwargs={'pk': self.id})

user/models.py
from django.db import models

Bookmark/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Bookmarks


def index(request):
    return render(request, 'mark.html')


def AddBookmark(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        url = request.POST.get('url')
        notes = request.POST.get('notes')
        author_id = request.user
        mark = Bookmarks(title=title, url=url, notes=notes, author=author_id)
        mark.save()
        return redirect('/')


class Delete_mark(View):
    def get(self, request, pk):
        mark = Bookmarks.objects.get(id=pk).delete()
        return redirect('/')

user/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.views import View
from django.contrib.auth.models import User


def Register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')

        if password != password2:
            messages.info(request, 'Пароли не совпадают')
            return redirect('/')
        elif User.objects.filter(username=username):
            messages.info(request, 'Это имя уже используется!')
            return redirect('/')
        else:
            user = User.objects.create_user(username=username, password=password)
            login(request, user)
            messages.success(request, 'Вы зарегестрировались!')
            return redirect('/')


def LoginUser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect('/')
        else:
            messages.info(request, 'Неверный логин или пароль')
            return redirect('/')


def Logout(request):
    logout(request)
    request.user = None
    return redirect('/')

templates/base.html
<!doctype html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="container" style="padding: 0; border: 4px solid #212529; border-radius: 25px;">
      <header>
          <nav class="navbar navbar-dark bg-dark" style="border-radius: 15px 15px 0px 0px;">
            <div class="container-fluid">
              <a class="navbar-brand" style="text-decoration: none;">Закладки</a>

<!--              <button type="button" class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#staticBackdrop">-->
<!--                Создать закладку-->
<!--              </button>-->

              {% if user.is_authenticated %}
                    <button type="button" class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#addBackdrop">
                      Создать закладку
                    </button>
                    <a href="{% url 'logout' %}"><button class="btn btn-outline-light">{{ user }}</button></a>
              {% else %}
                <div>
                    <button class="btn btn-outline-light " data-bs-toggle="modal" data-bs-target="#loginBackdrop">Войти</button>
                    <button class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#registerBackdrop">Регистрация</button>
                </div>
              {% endif %}

              {% include 'modal/login_modal.html'%}
              {% include 'modal/register_modal.html'%}
              {% include 'modal/add_modal.html'%}

            </div>
          </nav>
      </header>
      <div class="container">
        {% block content %}
        {% endblock content%}
      </div>
    </div>
  </body>
</html>

templates/mark.html
{% extends 'base.html' %}
{% load tags %}

{% block content %}


<!--{% include 'modal/add_modal.html'%}-->
{% for message in messages%}
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% if message.tags == 'info'%}
  <script>
    var m = '{{message}}'
    swal('Blocked!', m, 'info')
  </script>
{% elif message.tags == 'success'%}
  <script>
      var m = '{{message}}'
      swal(m, '', 'success')
   </script>
{%endif%}
{% endfor %}
<div class="row row-cols-1 row-cols-md-4 g-4" style="margin-top: 10px; padding: 0">
  {% get_mark_list user.id as mark_list%}
  {% for mark in mark_list %}
    <div class="col">
      <div class="card text-bg-dark mb-3" style="max-width: 18rem;">
        <div class="card-header">{{mark.create_at}}</div>
        <div class="card-body">
          <h5 class="card-title">{{mark.title}}</h5>
          {% if mark.notes|length >= 94%}
            <p class="card-text">{{mark.notes|slice:':94'}}...</p>
          {% else %}
            <p class="card-text">{{mark.notes}}</p>
          {% endif %}
          <a href="{{mark.get_absolute_url}}">
            <button type="button" class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
              Удалить
            </button>
          </a>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock content %}

templates/modal/add_modal.html
<div class="modal fade" id="addBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="addBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="addBackdropLabel">Создать закладку</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <form action="{% url 'add_mark' %}" method="POST" autocomplete="off">
            <div class="modal-body">
                {% csrf_token%}
                <div class="input-group mb-3 mt-3">
                    <span class="btn input-group-text border-secondary bg-light side-label">
                        <i class="fas fa-pen"></i>
                    </span>
                    <input type="text" class="form-control" name="title" placeholder="Заголовок">
                </div>
                <div class="input-group mb-1 mt-4">
                    <span class="btn input-group-text border-secondary bg-light side-label">
                        <i class="fas fa-at"></i>
                    </span>
                    <input type="url" class="form-control" name="url" placeholder="Url">
                </div>
                <div class="input-group mb-1 mt-4">
                    <span class="btn input-group-text border-secondary bg-light side-label">
                        <i class="fas fa-book"></i>
                    </span>
                    <input type="text" class="form-control" name="notes" placeholder="Примечание">
                </div>
            </div>
            <hr>
            <div class="container d-grid gap-2 mt-4 mb-4">
                  <button type="submit" class="btn btn-primary">Создать</button>
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
            </div>
        </form>
    </div>
  </div>
</div>

templates/modal/login_modal.html
<div class="modal fade" id="loginBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="loginBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="loginBackdropLabel">Войти</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <form action="{% url 'login_user' %}" method="POST" autocomplete="off">
            <div class="modal-body">
                {% csrf_token%}
                <div class="input-group mb-3 mt-3">
                    <span class="btn input-group-text border-secondary bg-light side-label">
                        <i class="fas fa-user-alt"></i>
                    </span>
                    <input type="text" class="form-control" name="username" placeholder="Username">
                </div>
                <div class="input-group mb-1 mt-4">
                    <span class="btn input-group-text border-secondary bg-light side-label">
                        <i class="fas fa-lock"></i>
                    </span>
                    <input type="password" class="form-control" name="password" placeholder="Password">
                </div>
            </div>
            <hr>
            <div class="container d-grid gap-2 mt-4 mb-4">
                  <button type="submit" class="btn btn-primary">Войти</button>
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
            </div>
        </form>
    </div>
  </div>
</div>


<!--<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">-->
<!--  <div class="modal-dialog">-->
<!--    <div class="modal-content">-->
<!--      <div class="modal-header">-->
<!--        <h5 class="modal-title" id="loginModalLabel">Войти</h5>-->
<!--        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>-->
<!--      </div>-->
<!--      <form action="{% url 'login_user' %}" method="POST" autocomplete="off">-->
<!--            <div class="modal-body">-->
<!--                {% csrf_token%}-->
<!--                <div class="input-group mb-3 mt-3">-->
<!--                    <span class="btn input-group-text border-secondary bg-light side-label">-->
<!--                        <i class="fas fa-user-alt"></i>-->
<!--                    </span>-->
<!--                    <input type="text" class="form-control" name="username" placeholder="Username">-->
<!--                </div>-->
<!--                <div class="input-group mb-3 mt-3">-->
<!--                    <span class="btn input-group-text border-secondary bg-light side-label">-->
<!--                        <i class="fas fa-lock"></i>-->
<!--                    </span>-->
<!--                    <input type="password" class="form-control" name="password" placeholder="Password">-->
<!--                </div>-->
<!--            </div>-->
<!--            <hr>-->
<!--            <div class="container d-grid gap-2 mt-4 mb-4">-->
<!--                  <a type="submit" class="btn btn-primary">Войти</a>-->
<!--                  <a type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</a>-->
<!--            </div>-->
<!--        </form>-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->

templates/modal/register_modal.html
<div class="modal fade" id="registerBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="registerBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="registerBackdropLabel">Регистрация</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <form action="{% url 'register' %}" method="POST" autocomplete="off">
            <div class="modal-body">
                {% csrf_token%}
                <div class="input-group mb-3 mt-3">
                    <span class="btn input-group-text border-secondary bg-light side-label">
                        <i class="fas fa-user-alt"></i>
                    </span>
                    <input type="text" class="form-control" name="username" placeholder="Username">
                </div>
                <div class="input-group mb-3 mt-4">
                    <span class="btn input-group-text border-secondary bg-light side-label">
                        <i class="fas fa-lock"></i>
                    </span>
                    <input type="password" class="form-control" name="password" placeholder="Password">
                </div>
                <div class="input-group mb-1 mt-4">
                    <span class="btn input-group-text border-secondary bg-light side-label">
                        <i class="fas fa-lock"></i>
                    </span>
                    <input type="password" class="form-control" name="password2" placeholder="Repeat password">
                </div>
            </div>
            <hr>
            <div class="container d-grid gap-2 mt-4 mb-4">
                  <button type="submit" class="btn btn-primary">Войти</button>
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
            </div>
        </form>
    </div>
  </div>
</div>

templates/test.html
<tr>
    <th><label for="id_title">Title:</label></th>
    <td>

      <input type="text" name="title" class="form-control" maxlength="100" required id="id_title">


    </td>
  </tr>

  <tr>
    <th><label for="id_url">Url:</label></th>
    <td>

      <input type="url" name="url" class="form-control" maxlength="200" id="id_url">


    </td>
  </tr>

  <tr>
    <th><label for="id_notes">Notes:</label></th>
    <td>

      <input type="text" name="notes" class="form-control" id="id_notes">




    </td>
  </tr>